### ISSUE TITLE
Server setup with test/demo system

### ISSUE THREAD

**Issue by sikell** [Zeta-Project/zeta#206]
Child of #205

**Comment by MarcelLuz** [comment]
**Config**
```
zeta {
  actor {
    cluster += "localhost:2551"
  }
}

akka {
  actor {
    provider = remote
  }
  remote {
    enabled-transports = ["akka.remote.netty.tcp"]
    # is provided by ClusterManager
    # netty.tcp {
    #   hostname = "127.0.0.1"
    #   port = 2552
    # }
  }
}

# Play mailer
play {
  mailer {
    host = smtp.gmail.com
    from = "iodfjvio@gmail.com"
    ssl = true
    port = 465
    user = "iodfjvio@gmail.com"
    password = jVcSwooo
    debug = true
  }

  # Secret key
  # ~~~~~
  # The secret key is used to secure cryptographics functions.
  # If you deploy your application to several instances be sure to use the same key!
  http.secret {
    key = ${APPLICATION_SECRET}
  }
}
include "shared.conf"

```

**Dockerfile**
```
FROM ubuntu:14.04

ENV SCALA_VERSION 2.12.6
ENV SBT_VERSION 1.1.6

RUN apt-get update && \
  apt-get install -y --no-install-recommends locales && \
  locale-gen en_US.UTF-8 && \
  apt-get dist-upgrade -y && \
  apt-get --purge remove openjdk* && \
  echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections && \
  echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java-trusty.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 && \
  apt-get update && \
  apt-get install -y --no-install-recommends oracle-java8-installer oracle-java8-set-default && \
  apt-get clean all

RUN apt-get remove scala-library scala && \
  wget --no-check-certificate www.scala-lang.org/files/archive/scala-$SCALA_VERSION.deb && \
  dpkg -i scala-$SCALA_VERSION.deb && \
  apt-get update && \
  apt-get install scala && \
  rm scala-$SCALA_VERSION.deb

RUN wget --no-check-certificate https://bintray.com/artifact/download/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  rm sbt-$SBT_VERSION.deb

WORKDIR /app
ENTRYPOINT ["sbt"]

```

**Docker-Compose**
```
version: '2'
services:
  mongodb:
    image: mongo:3.4.13
    volumes:
      - ./mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017

  api:
    image: zeta-sbt:1.0.6
    build: ./api
    volumes:
      - ./api:/app
      - ./sbt/server:/root
    environment:
      - APPLICATION_SECRET=superSecret
      - ZETA_MONGODB_SERVER=mongodb
      - ZETA_DEPLOYMENT=production
    stdin_open: true
    ports:
      - 9000:9000
    links:
      - mongodb
      - webapp
    command: ["-Dzeta.webapp.host=webapp", "project server", "run"]

  webapp:
    image: node:10.1.0 # Alpine cannot be used, because git executable is needed
    volumes:
      - ./webapp:/src
    command: "bash -c 'yarn; npm run dev'"
    working_dir: /src

```
